spring:
  application:
    name: api

  profiles:
    active: local

  datasource:
    hikari:
      data-source-properties:
        prepareThreshold: 0

portone:
  base-url: https://api.iamport.kr
  api-key: ${PORTONE_API_KEY:}
  api-secret: ${PORTONE_API_SECRET:}
